export default [
  "@opennetwork/environment",
  "@opennetwork/environments-schema-org-logistics",
  "@opennetwork/http-representation",
  "@opennetwork/progressive-merge",
  "@opennetwork/vnode",
  "@virtualstate/astro-renderer",
  "@virtualstate/dom",
  "@virtualstate/examples",
  "@virtualstate/fringe",
  "@virtualstate/hooks",
  "@virtualstate/hooks-extended",
  "@virtualstate/union",
  "@virtualstate/x",
  "dom-lite",
  "iterable",
  "uuid",
  "whatwg-url",
  "abort-controller"
] as const;