# At time of checking, node 16 is available here
# https://github.com/microsoft/playwright/blob/8f9eaf7cba53584436703bc7e35f27933c1a8c94/utils/docker/Dockerfile.focal#L12
FROM mcr.microsoft.com/playwright:focal